name = "catppuccin-latte"
kind = "light"

[palette]
bg = "#eff1f5"
panel = "#e6e9ef"
fg = "#4c4f69"
muted = "#8c8fa1"
accent = "#8839ef"
border = "#ccd0da"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#8839ef"
cyan = "#179299"
orange = "#fe640b"

[syntax]
keyword = "#8839ef"
string = "#40a02b"
comment = { fg = "#7c7f93", italic = true }
function = "#1e66f5"
type = "#df8e1d"
constant = "#fe640b"
number = "#fe640b"
operator = "#04a5e5"
variable = "fg"
property = "#7287fd"
punctuation = "#7c7f93"
attribute = "#df8e1d"
tag = "#1e66f5"
label = "#209fb5"
module = "#7287fd"
constructor = "#209fb5"
macro = "#d20f39"
escape = "#ea76cb"
embedded = "fg"
