name = "dracula"
kind = "dark"

[palette]
bg = "#282a36"
panel = "#21222c"
fg = "#f8f8f2"
muted = "#6272a4"
accent = "#bd93f9"
border = "#44475a"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#8be9fd"
magenta = "#ff79c6"
cyan = "#8be9fd"
orange = "#ffb86c"
purple = "#bd93f9"

[syntax]
keyword = "#ff79c6"
string = "#f1fa8c"
comment = { fg = "#6272a4", italic = true }
function = "#50fa7b"
type = { fg = "#8be9fd", italic = true }
constant = "purple"
number = "purple"
operator = "#ff79c6"
variable = "fg"
property = "fg"
punctuation = "fg"
attribute = "#50fa7b"
tag = "#ff79c6"
label = "#8be9fd"
module = "#8be9fd"
constructor = "purple"
macro = "#ff79c6"
escape = "#ff79c6"
embedded = "fg"
